accounts:
  - name: alice
    coins: ["20000token", "200000000stake", "2000000000uatom", "200000000uloan"]
  - name: bob
    coins: ["10000token", "100000000stake", "100000uatom", "20000uloan"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["5token", "100000stake", "200000000uloan"]
genesis:
  chain_id: "loan-1"
