// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: loan/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the loan module's genesis state.
type GenesisState struct {
	Params             Params          `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	LoanList           []Loan          `protobuf:"bytes,2,rep,name=loanList,proto3" json:"loanList"`
	LoanCount          uint64          `protobuf:"varint,3,opt,name=loanCount,proto3" json:"loanCount,omitempty"`
	TxHistoryList      []TxHistory     `protobuf:"bytes,4,rep,name=txHistoryList,proto3" json:"txHistoryList"`
	TxHistoryCount     uint64          `protobuf:"varint,5,opt,name=txHistoryCount,proto3" json:"txHistoryCount,omitempty"`
	DepositEarnedList  []DepositEarned `protobuf:"bytes,6,rep,name=depositEarnedList,proto3" json:"depositEarnedList"`
	DepositEarnedCount uint64          `protobuf:"varint,7,opt,name=depositEarnedCount,proto3" json:"depositEarnedCount,omitempty"`
	BorrowAccuredList  []BorrowAccured `protobuf:"bytes,8,rep,name=borrowAccuredList,proto3" json:"borrowAccuredList"`
	BorrowAccuredCount uint64          `protobuf:"varint,9,opt,name=borrowAccuredCount,proto3" json:"borrowAccuredCount,omitempty"`
	DepositList        []Deposit       `protobuf:"bytes,10,rep,name=depositList,proto3" json:"depositList"`
	DepositCount       uint64          `protobuf:"varint,11,opt,name=depositCount,proto3" json:"depositCount,omitempty"`
	BorrowList         []Borrow        `protobuf:"bytes,12,rep,name=borrowList,proto3" json:"borrowList"`
	BorrowCount        uint64          `protobuf:"varint,13,opt,name=borrowCount,proto3" json:"borrowCount,omitempty"`
	AprList            []Apr           `protobuf:"bytes,14,rep,name=aprList,proto3" json:"aprList"`
	AprCount           uint64          `protobuf:"varint,15,opt,name=aprCount,proto3" json:"aprCount,omitempty"`
	UserList           []User          `protobuf:"bytes,16,rep,name=userList,proto3" json:"userList"`
	UserCount          uint64          `protobuf:"varint,17,opt,name=userCount,proto3" json:"userCount,omitempty"`
	PoolList           []Pool          `protobuf:"bytes,18,rep,name=poolList,proto3" json:"poolList"`
	PoolCount          uint64          `protobuf:"varint,19,opt,name=poolCount,proto3" json:"poolCount,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a966099efcec6c8, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetLoanList() []Loan {
	if m != nil {
		return m.LoanList
	}
	return nil
}

func (m *GenesisState) GetLoanCount() uint64 {
	if m != nil {
		return m.LoanCount
	}
	return 0
}

func (m *GenesisState) GetTxHistoryList() []TxHistory {
	if m != nil {
		return m.TxHistoryList
	}
	return nil
}

func (m *GenesisState) GetTxHistoryCount() uint64 {
	if m != nil {
		return m.TxHistoryCount
	}
	return 0
}

func (m *GenesisState) GetDepositEarnedList() []DepositEarned {
	if m != nil {
		return m.DepositEarnedList
	}
	return nil
}

func (m *GenesisState) GetDepositEarnedCount() uint64 {
	if m != nil {
		return m.DepositEarnedCount
	}
	return 0
}

func (m *GenesisState) GetBorrowAccuredList() []BorrowAccured {
	if m != nil {
		return m.BorrowAccuredList
	}
	return nil
}

func (m *GenesisState) GetBorrowAccuredCount() uint64 {
	if m != nil {
		return m.BorrowAccuredCount
	}
	return 0
}

func (m *GenesisState) GetDepositList() []Deposit {
	if m != nil {
		return m.DepositList
	}
	return nil
}

func (m *GenesisState) GetDepositCount() uint64 {
	if m != nil {
		return m.DepositCount
	}
	return 0
}

func (m *GenesisState) GetBorrowList() []Borrow {
	if m != nil {
		return m.BorrowList
	}
	return nil
}

func (m *GenesisState) GetBorrowCount() uint64 {
	if m != nil {
		return m.BorrowCount
	}
	return 0
}

func (m *GenesisState) GetAprList() []Apr {
	if m != nil {
		return m.AprList
	}
	return nil
}

func (m *GenesisState) GetAprCount() uint64 {
	if m != nil {
		return m.AprCount
	}
	return 0
}

func (m *GenesisState) GetUserList() []User {
	if m != nil {
		return m.UserList
	}
	return nil
}

func (m *GenesisState) GetUserCount() uint64 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

func (m *GenesisState) GetPoolList() []Pool {
	if m != nil {
		return m.PoolList
	}
	return nil
}

func (m *GenesisState) GetPoolCount() uint64 {
	if m != nil {
		return m.PoolCount
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "loan.loan.GenesisState")
}

func init() { proto.RegisterFile("loan/genesis.proto", fileDescriptor_3a966099efcec6c8) }

var fileDescriptor_3a966099efcec6c8 = []byte{
	// 524 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x63, 0x1a, 0x92, 0x74, 0x9c, 0x26, 0x78, 0x28, 0x52, 0x88, 0x90, 0x89, 0x7a, 0x40,
	0x91, 0x90, 0x1c, 0x51, 0x0e, 0x48, 0x9c, 0x68, 0x00, 0xc1, 0x21, 0x87, 0xaa, 0xc0, 0x85, 0x4b,
	0xb4, 0x6d, 0xad, 0x10, 0x29, 0x78, 0x57, 0xeb, 0x8d, 0x48, 0xdf, 0x82, 0x37, 0xe0, 0x75, 0x7a,
	0xcc, 0x91, 0x13, 0x42, 0xc9, 0x8b, 0xa0, 0x9d, 0x59, 0x9b, 0x35, 0xe6, 0x12, 0x79, 0xbf, 0xf9,
	0xe6, 0xf7, 0xed, 0xdf, 0x00, 0xae, 0xa4, 0xc8, 0x26, 0x8b, 0x34, 0x4b, 0xf3, 0x65, 0x9e, 0x28,
	0x2d, 0x8d, 0xc4, 0x43, 0xab, 0x25, 0xf6, 0x67, 0x78, 0xbc, 0x90, 0x0b, 0x49, 0xea, 0xc4, 0x7e,
	0xb1, 0x61, 0x18, 0x51, 0x93, 0x12, 0x5a, 0x7c, 0x75, 0x3d, 0xc3, 0x3e, 0x49, 0xd4, 0xc8, 0xc2,
	0x03, 0x12, 0xcc, 0x66, 0xfe, 0x65, 0x99, 0x1b, 0xa9, 0x6f, 0x9c, 0xfc, 0x90, 0xe4, 0xeb, 0x54,
	0xc9, 0x7c, 0x69, 0xe6, 0xa9, 0xd0, 0x59, 0x7a, 0x5d, 0x29, 0x5d, 0x4a, 0xad, 0xe5, 0xb7, 0xb9,
	0xb8, 0xba, 0x5a, 0xeb, 0xb2, 0x84, 0x7e, 0x57, 0x65, 0x12, 0x6c, 0x77, 0x52, 0x8f, 0x24, 0xa1,
	0x74, 0x65, 0x52, 0xeb, 0x3c, 0xad, 0x0a, 0x4a, 0xca, 0x15, 0x0b, 0x27, 0x3f, 0xda, 0xd0, 0x7d,
	0xc7, 0x8b, 0xff, 0x60, 0x84, 0x49, 0x71, 0x02, 0x2d, 0x5e, 0xd7, 0x20, 0x18, 0x05, 0xe3, 0xf0,
	0x34, 0x4a, 0xca, 0xcd, 0x48, 0xce, 0xa9, 0x30, 0x6d, 0xde, 0xfe, 0x7a, 0xdc, 0xb8, 0x70, 0x36,
	0x7c, 0x06, 0x1d, 0x5b, 0x9c, 0x2d, 0x73, 0x33, 0xb8, 0x33, 0x3a, 0x18, 0x87, 0xa7, 0x7d, 0xaf,
	0x65, 0x26, 0x45, 0xe6, 0x1a, 0x4a, 0x1b, 0x3e, 0x02, 0xda, 0xe1, 0xd7, 0x72, 0x9d, 0x99, 0xc1,
	0xc1, 0x28, 0x18, 0x37, 0x2f, 0xfe, 0x0a, 0xf8, 0x0a, 0x8e, 0xcc, 0xe6, 0x3d, 0x6f, 0x1a, 0x51,
	0x9b, 0x44, 0x3d, 0xf6, 0xa8, 0x1f, 0x8b, 0xba, 0x43, 0x57, 0x1b, 0xf0, 0x09, 0xf4, 0x4a, 0x81,
	0x43, 0xee, 0x52, 0xc8, 0x3f, 0x2a, 0xce, 0x20, 0x72, 0x5b, 0xfa, 0x96, 0xce, 0x81, 0xd2, 0x5a,
	0x94, 0x36, 0xf0, 0xd2, 0xde, 0xf8, 0x1e, 0x97, 0x58, 0x6f, 0xc4, 0x04, 0xb0, 0x22, 0x72, 0x72,
	0x9b, 0x92, 0xff, 0x53, 0xb1, 0xe9, 0x7c, 0x78, 0x67, 0x7c, 0xd4, 0x94, 0xde, 0xa9, 0xa5, 0x4f,
	0x7d, 0x4f, 0x91, 0x5e, 0x6b, 0xb4, 0xe9, 0x15, 0x91, 0xd3, 0x0f, 0x39, 0xbd, 0x5e, 0xc1, 0x97,
	0x10, 0xba, 0x39, 0x51, 0x2e, 0x50, 0x2e, 0xd6, 0x57, 0xed, 0x12, 0x7d, 0x33, 0x9e, 0x40, 0xd7,
	0x0d, 0x39, 0x25, 0xa4, 0x94, 0x8a, 0x86, 0x2f, 0x00, 0x38, 0x95, 0xf0, 0x5d, 0xc2, 0x47, 0xb5,
	0x65, 0x39, 0xba, 0x67, 0xc5, 0x11, 0x84, 0x3c, 0x62, 0xf6, 0x11, 0xb1, 0x7d, 0x09, 0x13, 0x68,
	0x0b, 0xa5, 0x89, 0xdb, 0x23, 0x6e, 0xcf, 0xe3, 0x9e, 0x29, 0xed, 0xa0, 0x85, 0x09, 0x87, 0xd0,
	0x11, 0x4a, 0x33, 0xae, 0x4f, 0xb8, 0x72, 0x6c, 0x6f, 0xaf, 0x7d, 0x1e, 0x04, 0xbb, 0x57, 0xbb,
	0xbd, 0x9f, 0xf2, 0xb4, 0xa0, 0x95, 0x36, 0x7b, 0x7b, 0xed, 0x37, 0xf3, 0x22, 0xbe, 0xbd, 0xa5,
	0x60, 0x81, 0xf6, 0x79, 0x11, 0x10, 0x6b, 0xc0, 0x73, 0x29, 0x57, 0x05, 0xb0, 0xb0, 0x59, 0xa0,
	0xfd, 0x66, 0xe0, 0x7d, 0x06, 0x96, 0xc2, 0xf4, 0xe9, 0xed, 0x2e, 0x0e, 0xb6, 0xbb, 0x38, 0xf8,
	0xbd, 0x8b, 0x83, 0xef, 0xfb, 0xb8, 0xb1, 0xdd, 0xc7, 0x8d, 0x9f, 0xfb, 0xb8, 0xf1, 0x99, 0xff,
	0x00, 0x36, 0x13, 0xfe, 0xa3, 0xb9, 0x51, 0x69, 0x7e, 0xd9, 0xa2, 0x57, 0xfd, 0xfc, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xc3, 0xa8, 0xfd, 0x7a, 0xd6, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PoolCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.PoolCount))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if len(m.PoolList) > 0 {
		for iNdEx := len(m.PoolList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PoolList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x92
		}
	}
	if m.UserCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.UserCount))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if len(m.UserList) > 0 {
		for iNdEx := len(m.UserList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UserList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x82
		}
	}
	if m.AprCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.AprCount))
		i--
		dAtA[i] = 0x78
	}
	if len(m.AprList) > 0 {
		for iNdEx := len(m.AprList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AprList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x72
		}
	}
	if m.BorrowCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.BorrowCount))
		i--
		dAtA[i] = 0x68
	}
	if len(m.BorrowList) > 0 {
		for iNdEx := len(m.BorrowList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BorrowList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if m.DepositCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.DepositCount))
		i--
		dAtA[i] = 0x58
	}
	if len(m.DepositList) > 0 {
		for iNdEx := len(m.DepositList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DepositList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.BorrowAccuredCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.BorrowAccuredCount))
		i--
		dAtA[i] = 0x48
	}
	if len(m.BorrowAccuredList) > 0 {
		for iNdEx := len(m.BorrowAccuredList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BorrowAccuredList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.DepositEarnedCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.DepositEarnedCount))
		i--
		dAtA[i] = 0x38
	}
	if len(m.DepositEarnedList) > 0 {
		for iNdEx := len(m.DepositEarnedList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DepositEarnedList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.TxHistoryCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.TxHistoryCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.TxHistoryList) > 0 {
		for iNdEx := len(m.TxHistoryList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TxHistoryList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.LoanCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LoanCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.LoanList) > 0 {
		for iNdEx := len(m.LoanList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LoanList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.LoanList) > 0 {
		for _, e := range m.LoanList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.LoanCount != 0 {
		n += 1 + sovGenesis(uint64(m.LoanCount))
	}
	if len(m.TxHistoryList) > 0 {
		for _, e := range m.TxHistoryList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.TxHistoryCount != 0 {
		n += 1 + sovGenesis(uint64(m.TxHistoryCount))
	}
	if len(m.DepositEarnedList) > 0 {
		for _, e := range m.DepositEarnedList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.DepositEarnedCount != 0 {
		n += 1 + sovGenesis(uint64(m.DepositEarnedCount))
	}
	if len(m.BorrowAccuredList) > 0 {
		for _, e := range m.BorrowAccuredList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.BorrowAccuredCount != 0 {
		n += 1 + sovGenesis(uint64(m.BorrowAccuredCount))
	}
	if len(m.DepositList) > 0 {
		for _, e := range m.DepositList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.DepositCount != 0 {
		n += 1 + sovGenesis(uint64(m.DepositCount))
	}
	if len(m.BorrowList) > 0 {
		for _, e := range m.BorrowList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.BorrowCount != 0 {
		n += 1 + sovGenesis(uint64(m.BorrowCount))
	}
	if len(m.AprList) > 0 {
		for _, e := range m.AprList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.AprCount != 0 {
		n += 1 + sovGenesis(uint64(m.AprCount))
	}
	if len(m.UserList) > 0 {
		for _, e := range m.UserList {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if m.UserCount != 0 {
		n += 2 + sovGenesis(uint64(m.UserCount))
	}
	if len(m.PoolList) > 0 {
		for _, e := range m.PoolList {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if m.PoolCount != 0 {
		n += 2 + sovGenesis(uint64(m.PoolCount))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoanList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LoanList = append(m.LoanList, Loan{})
			if err := m.LoanList[len(m.LoanList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoanCount", wireType)
			}
			m.LoanCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LoanCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHistoryList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHistoryList = append(m.TxHistoryList, TxHistory{})
			if err := m.TxHistoryList[len(m.TxHistoryList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHistoryCount", wireType)
			}
			m.TxHistoryCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxHistoryCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositEarnedList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositEarnedList = append(m.DepositEarnedList, DepositEarned{})
			if err := m.DepositEarnedList[len(m.DepositEarnedList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositEarnedCount", wireType)
			}
			m.DepositEarnedCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositEarnedCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowAccuredList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BorrowAccuredList = append(m.BorrowAccuredList, BorrowAccured{})
			if err := m.BorrowAccuredList[len(m.BorrowAccuredList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowAccuredCount", wireType)
			}
			m.BorrowAccuredCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BorrowAccuredCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositList = append(m.DepositList, Deposit{})
			if err := m.DepositList[len(m.DepositList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositCount", wireType)
			}
			m.DepositCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BorrowList = append(m.BorrowList, Borrow{})
			if err := m.BorrowList[len(m.BorrowList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BorrowCount", wireType)
			}
			m.BorrowCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BorrowCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AprList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AprList = append(m.AprList, Apr{})
			if err := m.AprList[len(m.AprList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AprCount", wireType)
			}
			m.AprCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AprCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserList = append(m.UserList, User{})
			if err := m.UserList[len(m.UserList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserCount", wireType)
			}
			m.UserCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolList = append(m.PoolList, Pool{})
			if err := m.PoolList[len(m.PoolList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolCount", wireType)
			}
			m.PoolCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
